### ISSUE TITLE
Problem behind a proxy

### ISSUE THREAD

**Issue by sebDK** [grails/grails-wrapper#2]
Hi @jameskleeh ,

I am running grails 3.2.6 behind  a proxy. I am trying to run `grailsw.bat wrapper`
I got the following mistake:
`You must be connected to the internet the first time you use the Grails wrapper
java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at sun.net.NetworkClient.doConnect(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.openServer(Unknown Source)
        at sun.net.www.http.HttpClient.<init>(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.http.HttpClient.New(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        at grails.init.Start.getVersion(Start.java:34)
        at grails.init.Start.main(Start.java:79)`

I am running the code on a Windows 7 64 bits.

It looks like the problem is coming from this [line](https://github.com/grails/grails-wrapper/blob/master/starter/src/main/java/grails/init/Start.java#L36).

I tried to set proxy settings manually by running:
`grailsw.bat -Dhttp.proxyHost=http://myproxy.com -Dhttp.proxyPort=8080` but without success.

Any clue?

**Comment by jameskleeh** [comment]
Fixed in 3.2.7 https://github.com/grails/grails-core/issues/10465
